# Generated by Django 3.1.1 on 2023-01-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20230121_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_members',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
