# Generated by Django 3.1.1 on 2023-01-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_team_members_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='we_work_message',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
