# Generated by Django 3.1.1 on 2023-01-19 13:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0003_auto_20230119_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '6. Plot Category',
            },
        ),
        migrations.CreateModel(
            name='Plot_details_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(max_length=200)),
                ('block', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=2000)),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plot_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.plot_category')),
            ],
            options={
                'verbose_name': '5. Plot Detail of Table Society',
            },
        ),
        migrations.CreateModel(
            name='Plot_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '5. Plot Type',
            },
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor')),
            ],
            options={
                'verbose_name': '1. Society Name',
            },
        ),
        migrations.CreateModel(
            name='Society_Contact_Us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=2000)),
                ('phone_number', models.CharField(blank=True, max_length=2000)),
                ('Mobile_number', models.CharField(blank=True, max_length=2000)),
                ('whatsapp_number', models.CharField(blank=True, max_length=2000)),
                ('fb_id', models.CharField(blank=True, max_length=2000)),
                ('instagram_id', models.CharField(blank=True, max_length=2000)),
                ('gmail_id', models.CharField(blank=True, max_length=2000)),
                ('linkedin_id', models.CharField(blank=True, max_length=2000)),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('society', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='listings.society')),
            ],
            options={
                'verbose_name': '3. Society Contact Us',
            },
        ),
        migrations.CreateModel(
            name='Socity_latest_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '8. Society Latest News',
            },
        ),
        migrations.CreateModel(
            name='Socity_phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '7. Society Phase',
            },
        ),
        migrations.CreateModel(
            name='Socity_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '9. Society Status',
            },
        ),
        migrations.CreateModel(
            name='Society_Youtube_videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('yut_video_1', models.CharField(blank=True, max_length=2000)),
                ('yut_video_2', models.CharField(blank=True, max_length=2000)),
                ('yut_video_3', models.CharField(blank=True, max_length=2000)),
                ('yut_video_4', models.CharField(blank=True, max_length=2000)),
                ('yut_video_5', models.CharField(blank=True, max_length=2000)),
                ('yut_video_6', models.CharField(blank=True, max_length=2000)),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('society', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='listings.society')),
            ],
            options={
                'verbose_name': '2. Society Youtube Videos',
            },
        ),
        migrations.CreateModel(
            name='Society_Home_Page_Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_7', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_8', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_9', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_10', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('society', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='listings.society')),
            ],
            options={
                'verbose_name': '4. Society Home Page Images',
            },
        ),
        migrations.CreateModel(
            name='Society_details_home_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=200)),
                ('launch_date', models.CharField(max_length=1000)),
                ('approvals', models.CharField(max_length=1000)),
                ('facilities', models.CharField(max_length=2000)),
                ('transfer_charges', models.CharField(max_length=2000)),
                ('transfer_office', models.CharField(max_length=2000)),
                ('location_on_map', models.CharField(max_length=1000)),
                ('society_location', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('official_website', models.CharField(max_length=1000)),
                ('official_contact_number', models.CharField(max_length=1000)),
                ('posession', models.BooleanField(default=False)),
                ('posession_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('description_and_details_1', tinymce.models.HTMLField(blank=True)),
                ('description_and_details_2', tinymce.models.HTMLField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plot_details_table', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.plot_details_table')),
                ('plot_types', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.plot_types')),
                ('society', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='listings.society')),
                ('society_contact_us', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.society_contact_us')),
                ('society_home_page_images', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.society_home_page_images')),
                ('society_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.socity_status')),
                ('society_youtube_videos', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.society_youtube_videos')),
            ],
            options={
                'verbose_name': '6. Society Detail Home Page',
            },
        ),
        migrations.AddField(
            model_name='plot_details_table',
            name='plot_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.plot_types'),
        ),
        migrations.AddField(
            model_name='plot_details_table',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.society'),
        ),
        migrations.AddField(
            model_name='plot_details_table',
            name='society_phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.socity_phase'),
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200, null=True)),
                ('description', tinymce.models.HTMLField(blank=True)),
                ('video_url', models.CharField(max_length=1000, null=True)),
                ('price', models.IntegerField(null=True)),
                ('bedrooms', models.IntegerField(null=True)),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('garage', models.IntegerField(default=0)),
                ('square_foot', models.IntegerField(null=True)),
                ('plot_size', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('photo_main', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('society', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='listings.society')),
            ],
            options={
                'verbose_name': '7. Plot Listing',
            },
        ),
    ]
