# Generated by Django 4.1.4 on 2023-01-19 00:05

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
