# Generated by Django 3.1.1 on 2023-01-23 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='society_phase_details_home_page',
            name='plot_phase_details_table',
        ),
    ]
