# Generated by Django 3.1.1 on 2023-01-21 08:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='society_phase_details_home_page',
            name='sector',
        ),
        migrations.CreateModel(
            name='Socity_phase_Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('society', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='listings.society')),
                ('society_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.socity_phase')),
                ('society_sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.socity_sector')),
            ],
            options={
                'verbose_name': '20. Society Phase and Sector',
            },
        ),
    ]
