# Generated by Django 3.1.1 on 2023-01-21 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20230121_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society_phase_details_home_page',
            name='launch_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
