# Generated by Django 3.1.1 on 2023-01-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_society_phase_details_home_page_plot_phase_details_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society_phase_details_home_page',
            name='download_location_file',
            field=models.FileField(blank=True, upload_to='locationMap/%Y/%m/%d/'),
        ),
    ]
