# Generated by Django 3.1.1 on 2023-01-21 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20230121_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='society_phase_details_home_page',
            name='society_phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.socity_phase'),
        ),
    ]
