# Generated by Django 3.1.1 on 2023-01-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20230124_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society_details_home_page',
            name='download_location_file',
            field=models.FileField(blank=True, upload_to='locationMap/%Y/%m/%d/'),
        ),
    ]
