# Generated by Django 3.1.1 on 2023-01-17 10:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_plot_category_plot_types_socity_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot_details_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(max_length=200)),
                ('block', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('contact', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=2000)),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('plot_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.plot_category')),
                ('plot_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.plot_types')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.society')),
                ('society_phase', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.socity_phase')),
            ],
        ),
    ]
