# Generated by Django 3.1.1 on 2023-01-22 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_society_phase_details_home_page_society_phase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='society',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='society_phase',
        ),
        migrations.AddField(
            model_name='listing',
            name='socity_phase_sector',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='listings.socity_phase_sector'),
        ),
    ]
