# Generated by Django 3.1.1 on 2023-01-24 10:53

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20230124_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society_phase_youtube_videos',
            name='yut_video_1',
            field=embed_video.fields.EmbedVideoField(),
        ),
        migrations.AlterField(
            model_name='society_phase_youtube_videos',
            name='yut_video_2',
            field=embed_video.fields.EmbedVideoField(),
        ),
        migrations.AlterField(
            model_name='society_phase_youtube_videos',
            name='yut_video_3',
            field=embed_video.fields.EmbedVideoField(),
        ),
        migrations.AlterField(
            model_name='society_phase_youtube_videos',
            name='yut_video_4',
            field=embed_video.fields.EmbedVideoField(),
        ),
        migrations.AlterField(
            model_name='society_phase_youtube_videos',
            name='yut_video_5',
            field=embed_video.fields.EmbedVideoField(),
        ),
        migrations.AlterField(
            model_name='society_phase_youtube_videos',
            name='yut_video_6',
            field=embed_video.fields.EmbedVideoField(),
        ),
        migrations.AlterField(
            model_name='society_youtube_videos',
            name='yut_video_2',
            field=embed_video.fields.EmbedVideoField(),
        ),
        migrations.AlterField(
            model_name='society_youtube_videos',
            name='yut_video_3',
            field=embed_video.fields.EmbedVideoField(),
        ),
        migrations.AlterField(
            model_name='society_youtube_videos',
            name='yut_video_4',
            field=embed_video.fields.EmbedVideoField(),
        ),
        migrations.AlterField(
            model_name='society_youtube_videos',
            name='yut_video_5',
            field=embed_video.fields.EmbedVideoField(),
        ),
        migrations.AlterField(
            model_name='society_youtube_videos',
            name='yut_video_6',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
