# Generated by Django 3.1.1 on 2023-01-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20230122_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='block',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='plot_no',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
