# Generated by Django 4.1.5 on 2023-01-24 12:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_new_city_alter_city_id_alter_listing_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society_phase_details_home_page',
            name='description_and_details_1',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
