# Generated by Django 4.1.5 on 2023-01-24 12:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_alter_society_phase_details_home_page_description_and_details_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='society_details_home_page',
            name='description_and_details_1',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='society_details_home_page',
            name='description_and_details_2',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='society_phase_details_home_page',
            name='description_and_details_2',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
