# Generated by Django 4.1.5 on 2023-01-24 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_listing_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='new_city',
        ),
    ]
