# Generated by Django 3.1.1 on 2023-01-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20230122_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socity_rating',
            name='rate',
            field=models.CharField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, max_length=5, null=True),
        ),
    ]
