# Generated by Django 4.1.5 on 2023-01-24 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_delete_new_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society_home_page_images',
            name='society',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='listings.society', unique=True),
        ),
    ]
