# Generated by Django 4.1.5 on 2023-01-24 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_alter_socity_phase_sector_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='society_details_home_page',
            unique_together={('society', 'society_youtube_videos', 'society_home_page_images')},
        ),
        migrations.AlterUniqueTogether(
            name='society_phase_details_home_page',
            unique_together={('society', 'society_phase_youtube_videos', 'society_phase_home_page_images', 'society_phase')},
        ),
        migrations.AlterUniqueTogether(
            name='society_phase_home_page_images',
            unique_together={('society', 'society_phase')},
        ),
        migrations.AlterUniqueTogether(
            name='society_phase_youtube_videos',
            unique_together={('society', 'society_phase')},
        ),
    ]
