# Generated by Django 4.1.5 on 2023-01-25 02:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_alter_society_phase_youtube_videos_yut_video_1_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='society_details_home_page',
            unique_together={('society',)},
        ),
        migrations.AlterUniqueTogether(
            name='society_phase_details_home_page',
            unique_together={('society', 'society_phase')},
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='society_details_home_page',
            name='description_and_details_1',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='society_details_home_page',
            name='description_and_details_2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='society_phase_details_home_page',
            name='description_and_details_1',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='society_phase_details_home_page',
            name='description_and_details_2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
