# Generated by Django 4.1.5 on 2023-01-26 06:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_alter_society_details_home_page_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socity_transfer_office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=200)),
                ('office_contact_no', models.CharField(max_length=200)),
                ('office_address', models.CharField(max_length=1000)),
                ('office_google_map', models.CharField(max_length=1000)),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('society', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='listings.society')),
                ('society_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.socity_phase')),
            ],
            options={
                'verbose_name': '13. Society Transfer Office',
            },
        ),
    ]
