# Generated by Django 4.1.5 on 2023-01-26 06:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_socity_transfer_office'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socity_transfer_office',
            options={'verbose_name': '21. Society Transfer Office'},
        ),
        migrations.AddField(
            model_name='socity_transfer_office',
            name='description_and_details',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
