# Generated by Django 4.1.5 on 2023-01-26 07:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_alter_socity_transfer_office_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society_details_home_page',
            name='transfer_charges',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
