# Generated by Django 4.1.5 on 2023-01-26 10:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_alter_society_details_home_page_transfer_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society_phase_details_home_page',
            name='transfer_charges',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
